spring:

  # Mysql Configuration

    ## Mysql datasource configuration
    datasource:
        url: jdbc:mysql://localhost:3306/c1adb?useSSL=false
        username: c1adb
        password: newpass1
        driver-class-name: com.mysql.jdbc.Driver

    ## Mysql JPA configuration : This is not mandatory. Use it only if you need to customize the JPA configuration
    jpa:
        database: MYSQL
        hibernate:
            ddl-auto: validate
            dialect: org.hibernate.dialect.MySQL5Dialect

  # Oracle configuration

    ##Oracle datasource configuration
    #dataSourceClassName: oracle.jdbc.pool.OracleDataSource
    #   url: jdbc:oracle:thin:@localhost:1521/orcl
    #   password: newpass1
    #   username: C1ADB_LOCAL
    #   driver-class-name: oracle.jdbc.OracleDriver

    ## Oracle JPA configuration : This is not mandatory. Use it only if you need to customize the JPA configuration
    #jpa:
    #   properties:
    #      hibernate: &hibernate
    #          show_sql: false
    #          format_sql: false
    #          order_inserts: true
    #          order_updates: true
    #          jdbc:
    #             batch_size: 100
    #          cache:
    #             use_query_cache: false
    #             use_second_level_cache: false
    #
    ## Use the below config if you are using inmemory db
    #      primary:
    #           hibernate:
    #             dialect: org.hibernate.dialect.Oracle10gDialect
    #           hbm2ddl:
    #             auto: none

#logging:
#  level:
#    ROOT: DEBUG